import pandas as pd
from docx import Document
from docx2pdf import convert
import smtplib
from email.message import EmailMessage
from datetime import datetime
import os

if not os.path.exists("reports"):
    os.makedirs("reports")

data = pd.read_excel("data.xlsx")

print("Starting REGETORI...")

for index, row in data.iterrows():
    try:
        name = str(row["Name"])
        last_name = str(row["LastName"])
        email = str(row["Email"])
        score = str(row["Score"])
        course = str(row["Course"])
        studentid = str(row["StudentID"])
    
        score_int = int(score)
        
        if score_int >= 90:
            grade = "5"
            feedback = "Excellent performance"
        elif score_int >= 75:
            grade = "4"
            feedback = "Good performance"
        elif score_int >= 60:
            grade = "3"
            feedback = "Decent performance"
        else:
            grade = "2"
            feedback = "Needs improvement"
                    
        if score_int >= 50:
            status = "PASS"
        else:
            status = "FAIL"
            
        import random
        report_id = random.randint(1000, 9999)

        print(f"\nCreating report for {name}")

        today = datetime.today().strftime("%d.%m.%Y")

        doc = Document("template.docx")

        for paragraph in doc.paragraphs:
            if "{{Name}}" in paragraph.text:
                paragraph.text = paragraph.text.replace("{{Name}}", name)

            if "{{LastName}}" in paragraph.text:
                paragraph.text = paragraph.text.replace("{{LastName}}", last_name)

            if "{{Score}}" in paragraph.text:
                paragraph.text = paragraph.text.replace("{{Score}}", score)

            if "{{Date}}" in paragraph.text:
                paragraph.text = paragraph.text.replace("{{Date}}", today)
                
            if "{{Course}}" in paragraph.text:
                paragraph.text = paragraph.text.replace("{{Course}}", course)
                
            if "{{Feedback}}" in paragraph.text:
                paragraph.text = paragraph.text.replace("{{Feedback}}", feedback)
            
            if "{{ReportID}}" in paragraph.text:
                paragraph.text = paragraph.text.replace("{{ReportID}}", str(report_id))
            
            if "{{StudentID}}" in paragraph.text:
                paragraph.text = paragraph.text.replace("{{StudentID}}", studentid)
                
            if "{{Grade}}" in paragraph.text:
                paragraph.text = paragraph.text.replace("{{Grade}}", grade)
                
            if "{{Status}}" in paragraph.text:
                paragraph.text = paragraph.text.replace("{{Status}}", status)
            

        docx_filename = f"reports/{name}.docx"
        doc.save(docx_filename)

        pdf_filename = f"reports/{name}_{today}.pdf"
        convert(docx_filename, pdf_filename)

        msg = EmailMessage()
        msg["Subject"] = f"Report for {name} – {course}"
        msg["From"] = "milla.salomaa@gmail.com"
        msg["To"] = email
        msg.set_content(f"""
Hello {name},

Your report has been successfully generated by the REGETORI automation system.

Report Details:
Course: {course}
Score: {score}
Grade: {grade}
Date: {today}

The report is attached to this email as a PDF file.

If you have any questions or notice any issues, please contact support.

Best regards,
REGETORI Robot
Automated Report System Created by Martin Smerling and Milla Salomaa
""")

        with open(pdf_filename, "rb") as f:
            msg.add_attachment(
                f.read(),
                maintype="application",
                subtype="pdf",
                filename=f"{name}.pdf"
            )

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login("milla.salomaa@gmail.com", "jqqkmeoubxmdqepo")
            smtp.send_message(msg)

        print(f"Report successfully sent to {email}")
        
        with open("log.txt", "a") as log:
            log.write(f"{name} report sent to {email} on {today}\n")

    except Exception as e:
        print(f"Error with {row}: {e}")
        
        with open("log.txt", "a") as log:
            log.write(f"ERROR with {name}: {e}\n")

print("\nALL REPORTS COMPLETED ✅")